version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(levelname)s:     %(message)s"
  access:
    format: "%(levelname)s:     %(client_addr)s - \"%(request_line)s\" %(status_code)s"
handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: false
root:
  level: INFO
  handlers: []
